# ------------------------------------------------
# INCLUSIONS -------------------------------------
# ------------------------------------------------
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

local: &local
  username: ubermonkey_server
  password: ubermonkey_server
  host: localhost
  port: 5432

# ------------------------------------------------
# ENVIRONMENTS -----------------------------------
# ------------------------------------------------
development:
  <<: *default
  <<: *local
  database: ubermonkey_server_development

test:
  <<: *default
  <<: *local
  database: ubermonkey_server_test

production:
  <<: *default
  database: ubermonkey_server_production
  username: ubermonkey_server
  password: <%= ENV['UBERMONKEY_SERVER_DATABASE_PASSWORD'] %>
