default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

local: &local
  username: tampermonkey_server
  password: tampermonkey
  host: localhost
  port: 5432

development:
  <<: *default
  <<: *local
  database: tampermonkey_server_development

test:
  <<: *default
  <<: *local
  database: tampermonkey_server_test

production:
  <<: *default
  database: tampermonkey_server_production
  username: tampermonkey_server
  password: <%= ENV['TAMPERMONKEY_SERVER_DATABASE_PASSWORD'] %>
